# Coastal NMF

In [4]:
# imports
from importlib import reload
from importlib.resources import files
import os
import numpy as np

from scipy.optimize import curve_fit
from scipy.io import matlab

import pandas
import seaborn as sns
from matplotlib import pyplot as plt

from scipy.interpolate import interp1d

from ocpy.hydrolight import loisel23
from ocpy.utils import plotting as oc_plotting

from cnmf.oceanography import utils as co_utils
from cnmf import nmf_imaging
from cnmf import stats as cnmf_stats

In [3]:
%matplotlib ipympl

# Load me up

In [5]:
dfile = os.path.join(os.getenv('OS_COLOR'), 'data', 'Florida', 'input_params_only_T17SaborViirs.mat')
d = matlab.loadmat(dfile)

In [7]:
d.keys()

dict_keys(['__header__', '__version__', '__globals__', 'params_closure', 'params_sabor', 'params_viirs'])

## Dig in

### params_closure

In [11]:
d['params_closure'].dtype

dtype([('chla_closure', 'O'), ('sza_closure', 'O'), ('rrs_closure', 'O'), ('Rrs_closure', 'O'), ('Es_closure', 'O'), ('IOP_lambda', 'O'), ('bbpbp_closure', 'O'), ('bbt_closure', 'O'), ('at_closure', 'O'), ('minRrs', 'O'), ('aw_closure', 'O'), ('depo10', 'O'), ('nwl', 'O'), ('wlidx', 'O'), ('wl_closure', 'O'), ('npts', 'O'), ('Es_lambda', 'O'), ('input_dataset_def', 'O'), ('sst', 'O'), ('sal', 'O'), ('apg_closure', 'O'), ('bbp_closure', 'O')])

In [26]:
d['params_closure']['rrs_closure'][0,0].shape

(23, 7)

In [17]:
d['params_closure']['wl_closure'][0,0]

array([[412, 440, 488, 510, 532, 555, 650]], dtype=uint16)

In [22]:
d['params_closure']['nwl'][0]

array([array([[7]], dtype=uint8)], dtype=object)

### params_sabor

In [18]:
d['params_sabor'].dtype

dtype([('sza_sabor', 'O'), ('rrs_sabor', 'O'), ('Rrs_sabor', 'O'), ('Es_sabor', 'O'), ('IOP_lambda', 'O'), ('bbpbp_sabor', 'O'), ('bbpbp', 'O'), ('bbt_sabor', 'O'), ('at_sabor', 'O'), ('minRrs', 'O'), ('aw_sabor', 'O'), ('depo10', 'O'), ('nwl', 'O'), ('wlidx', 'O'), ('wl_sabor', 'O'), ('npts', 'O'), ('Es_lambda', 'O'), ('input_dataset_def', 'O'), ('sst', 'O'), ('sal', 'O'), ('apg_sabor', 'O'), ('bbp_sabor', 'O')])

In [20]:
d['params_sabor']['wl_sabor'][0,0]

array([[412, 440, 488, 510, 532, 555, 650]], dtype=uint16)

In [27]:
d['params_sabor']['rrs_sabor'][0,0].shape

(12, 7)

### VIIRS

In [21]:
d['params_viirs']['wl_viirs'][0,0]

array([[412, 440, 488, 510, 532, 555, 650]], dtype=uint16)