# Coastal NMF (Florida)

In [2]:
# imports
from importlib import reload
from importlib.resources import files
import os
import numpy as np

from scipy.optimize import curve_fit
from scipy.io import matlab

import pandas
import seaborn as sns
from matplotlib import pyplot as plt

from scipy.interpolate import interp1d

from ocpy.hydrolight import loisel23
from ocpy.utils import plotting as oc_plotting

from cnmf.oceanography import utils as co_utils
from cnmf import nmf_imaging
from cnmf import stats as cnmf_stats

In [3]:
%matplotlib ipympl

# Load me up

In [4]:
#dfile = os.path.join(os.getenv('OS_COLOR'), 'data', 'Florida', 'input_params_only_T17SaborViirs.mat')
dfile = os.path.join(os.getenv('OS_COLOR'), 'data', 'Florida', 'viirs_Rrs_IOPs_20N.mat')
d = matlab.loadmat(dfile)

/home/xavier/miniconda3/envs/os_11/lib/python3.11/site-packages/scipy/io/matlab/_mio.py:227: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [5]:
d.keys()

dict_keys(['__header__', '__version__', '__globals__', 'None', 'Ed_HL_viirs2', 'Fo_viirs', 'Lat_Lon_Rrs_viirs2', 'LwN_viirs2', 'Rrs_viirs2', 'depth_weight_iops2_acswav', 'lambda_viirs', 'wl_Ed_HL_viirs2', '__function_workspace__'])

## Dig in

In [7]:
d['lambda_viirs'].shape

(135, 1)

In [12]:
d['lambda_viirs'][0:30]

array([[352.16],
       [355.48],
       [358.81],
       [362.14],
       [365.47],
       [368.79],
       [372.12],
       [375.45],
       [378.78],
       [382.11],
       [385.44],
       [388.77],
       [392.1 ],
       [395.44],
       [398.77],
       [402.1 ],
       [405.43],
       [408.76],
       [412.1 ],
       [415.43],
       [418.76],
       [422.1 ],
       [425.43],
       [428.77],
       [432.1 ],
       [435.43],
       [438.77],
       [442.1 ],
       [445.44],
       [448.78]])

In [8]:
d['Lat_Lon_Rrs_viirs2'].shape

(2, 20)

In [9]:
d['wl_Ed_HL_viirs2'].shape

(17, 1)

In [10]:
d['LwN_viirs2'].shape

(135, 20)

### params_sabor

In [18]:
d['params_sabor'].dtype

dtype([('sza_sabor', 'O'), ('rrs_sabor', 'O'), ('Rrs_sabor', 'O'), ('Es_sabor', 'O'), ('IOP_lambda', 'O'), ('bbpbp_sabor', 'O'), ('bbpbp', 'O'), ('bbt_sabor', 'O'), ('at_sabor', 'O'), ('minRrs', 'O'), ('aw_sabor', 'O'), ('depo10', 'O'), ('nwl', 'O'), ('wlidx', 'O'), ('wl_sabor', 'O'), ('npts', 'O'), ('Es_lambda', 'O'), ('input_dataset_def', 'O'), ('sst', 'O'), ('sal', 'O'), ('apg_sabor', 'O'), ('bbp_sabor', 'O')])

In [20]:
d['params_sabor']['wl_sabor'][0,0]

array([[412, 440, 488, 510, 532, 555, 650]], dtype=uint16)

In [27]:
d['params_sabor']['rrs_sabor'][0,0].shape

(12, 7)

### VIIRS

In [21]:
d['params_viirs']['wl_viirs'][0,0]

array([[412, 440, 488, 510, 532, 555, 650]], dtype=uint16)